name: shared_widget
description: "公共组件--UI组件"
version: 1.0.0
homepage: 
publish_to: none

environment:
  sdk: '>=3.9.0<4.0.0'
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter

  #badge
  badges: ^3.1.2

  flutter_screenutil: ^5.9.3

  # 拍照、相册
  wechat_assets_picker: ^9.5.1
  wechat_camera_picker: ^4.3.7

  # 下拉刷新
  easy_refresh: ^3.4.0

  # 瀑布流布局
  waterfall_flow: ^3.1.1

  # loading组件
  # loader_overlay: ^5.0.0
  # flutter_easyloading: ^3.0.5

  ##########################

  #跑马灯
  # marquee: ^2.3.0

  # 二维码扫描
  # mobile_scanner: ^4.0.1
  # native_barcode_scanner: ^1.0.11

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
