name: feature_debug
description: "feature_debug"
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.0<4.0.0'
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2

  core:
    path: ../../core

  shared:
    path: ../../shared

dev_dependencies:
  flutter_lints: ^6.0.0

flutter: