name: core
description: "基础组件库"
version: 1.0.0

environment:
  sdk: '>=3.9.0<4.0.0'
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter

  #网络请求
  dio: ^5.9.0

  #日志
  talker_flutter: ^5.0.0
  talker_dio_logger: ^5.0.0
  talker_logger: ^5.0.0

  # for value storage
  shared_preferences: ^2.5.3
  # for file storage
  path_provider: ^2.1.5

  # 权限
  permission_handler: ^12.0.0+1

  # 加密
  crypto: ^3.0.6
  encrypt: ^5.0.3

  # svg
  flutter_svg: ^2.1.0
  # 网络图片
  cached_network_image: ^3.4.1

  # 包信息、设备信息
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0

  # 打开系统设置页面
  app_settings: ^6.1.1

  # 拉起外部导航应用
  map_launcher: ^3.5.0

  # 网络状态
  connectivity_plus: ^6.1.4

  # 跳转
  url_launcher: ^6.3.1
  app_links: ^6.4.0

  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
